# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: jake
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://jake:mypassword@db:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  postgres_data:
